DROP TABLE IF EXISTS mutations;
DROP TABLE IF EXISTS tombstones;
DROP TABLE IF EXISTS download_requests;
DROP TABLE IF EXISTS measurements;
DROP TABLE IF EXISTS reading_states;
DROP TABLE IF EXISTS locations;
DROP TABLE IF EXISTS entries;
ALTER TABLE IF EXISTS collections DROP CONSTRAINT IF EXISTS preferred_source_belongs_to_collection;
DROP TABLE IF EXISTS sources;
DROP TABLE IF EXISTS collections;
DROP TABLE IF EXISTS folders;
DROP TABLE IF EXISTS libraries;
