/// What this build calls itself.
///
/// **Generated by `tool/release.sh` and checked in.** It is a plain constant
/// rather than a runtime read of the bundle for two reasons: nothing in the app
/// should have to await a platform channel to print its own version, and a
/// constant is readable by a test — `test/version_test.dart` pins it to
/// `pubspec.yaml`, so the number the app shows and the number the store gets
/// cannot drift apart.
///
/// [kAppVersion] is the marketing version (`CFBundleShortVersionString`,
/// Android's `versionName`). [kAppBuild] is the build number
/// (`CFBundleVersion`, `versionCode`) — it only ever goes up, including across
/// versions, because both stores refuse an upload that reuses one.
library;

const String kAppVersion = '1.0.0';

const int kAppBuild = 1;

/// `1.0.0 (1)` — the app's own way of naming a build, in one place so the
/// Settings footer, a bug report and a log line all say it the same way.
String get appVersionLabel => '$kAppVersion ($kAppBuild)';
